version: '3.5'
services:
  # cloud-sync:
  #   image: cloud-sync
  #   container_name: cloud-sync
  #   command: 
  #   - --filepath="/Users/wangxiong/Desktop/github"
  #   - --alist_src="/local/data" 
  #   - --alist_dir="/百度网盘/数据冷备" 
  #   - --alist_host="http://localhost:5244" 
  #   - --alist_data_dir="/Users/wangxiong/alist" 
  #   - --alist_token="alist-88bb6ecc-ae41-43b4-b74b-6b104bfa3032I1xheiJw34zUSaI7FQl1JptaI584AO2cGAIIvUwtUGTRWWg4haBztKkqjVqgX67f"
  #   volumes:
  #     - "/Users/wangxiong/Desktop/iphone12:/root/data"
  aliyunpan-sync:
    image: tickstep/aliyunpan-sync:v0.2.7
    restart: always
    volumes:
      - "/Users/wangxiong/Desktop/iphone12:/home/app/data"
    environment:
      - TZ=Asia/Shanghai
      # token获取：打开阿里云盘，console输入 JSON.parse(localStorage.getItem("token")).refresh_token
      - ALIYUNPAN_REFRESH_TOKEN=07f24d5b86ce4c2bbbebd186bb289f9b
      - ALIYUNPAN_PAN_DIR=/阿里云盘数据同步
      - ALIYUNPAN_SYNC_MODE=sync # 双向同步
      - ALIYUNPAN_TASK_STEP=sync
      # - ALIYUNPAN_VERBOSE=1 # 调试日志
    container_name: aliyunpan-sync
  alist:
    image: xhofe/alist:latest
    restart: always
    volumes:
      - "/Users/wangxiong/alist:/opt/alist/data" 
    ports:
      - 5244:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    container_name: alist
  photoprism:
    container_name: photoprism
    image: registry.cn-hangzhou.aliyuncs.com/breawang/photoprism:latest
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"                 # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: "admin"             # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DISABLE_TLS: "false"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 10000              # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
    volumes:
      - "~/Desktop/iphone12:/photoprism/originals/pictures"
      - "/Users/wangxiong/Desktop/github/photoprism/import:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "/Users/wangxiong/Desktop/github/photoprism/storage:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: mariadbd --lower-case-table-names=1 --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "database:/var/lib/mysql" # Named volume "database" is defined at the bottom (DO NOT REMOVE)
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "insecure"
      MARIADB_ROOT_PASSWORD: "insecure"
volumes:
  database:
    driver: local