name: Build Docker Image

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["master"]
  release:
    types: [published]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to hub.docker.com
        run: docker login --username=oldwang6 -p ${{ secrets.HUB_PASSWORD }}

      - name: Build amd64 image
        run: make build-amd64

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to hub.docker.com
        run: docker login --username=oldwang6 -p ${{ secrets.HUB_PASSWORD }}

      - name: Build arm64 image
        run: make build-arm64

  build-arm-v7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to hub.docker.com
        run: docker login --username=oldwang6 -p ${{ secrets.HUB_PASSWORD }}

      - name: Build arm v7 image
        run: make build-arm-v7
